platform :ios, '10.0'

target 'Gas' do
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya', '~> 14.0'
  pod 'SwiftGen', '~> 6.0'
  pod 'KeychainSwift', '~> 19.0'
  pod 'PPBlinkOCR', '~> 5.0.0'
end
